require: rubocop-rake

AllCops:
  TargetRubyVersion: 3.2
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - "Gemfile"
    - "tmp/**/*"
    - "metadata-1.0/**/*"
    - "metadata-aardvark/**/*"

Metrics/AbcSize:
  Max: 20
