name: update

on:
  workflow_dispatch:
  schedule:
    - cron: '12 6 * * MON'

permissions:
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - run: git checkout -b data-updates
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      - run: bundle exec rake
        env:
          STACKS_TOKEN: ${{ secrets.STACKS_TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Update Stanford data dump'
          branch: data-updates
          push_options: '--force'
      - name: pull-request
        run: |
          gh_pr_up() { gh pr create $* || gh pr edit $*; }
          gh_pr_up --title "Update Stanford data dump" --head data-updates
